name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: { branches: { include: [master] } }
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

schedules:
  - cron: "0 0 * * *"
    displayName: Nightly Build
    branches: { include: [ master ] }

stages:

  - stage: Build
    displayName: Build
    pool: { vmImage: windows-latest }
    jobs:
    - job: Build
      steps:
      - template: /steps/netcore/version.yaml@templates

      - template: /steps/netcore/restore.yaml@templates
        parameters: { projects: '**/*.csproj' }

      - template: /steps/netcore/build.yaml@templates
        parameters: { projects: '**/*.csproj' }

      - template: /steps/netcore/test.yaml@templates
        parameters: { projects: '**/*.csproj' }

      - task: NuGetCommand@2
        displayName: Pack
        inputs:
          command: 'pack -IncludeReferencedProjects'
          configuration: 'release'
          packagesToPack: '$(Build.SourcesDirectory)/**/*.csproj'
          versioningScheme: 'off'

      - template: /steps/package/publish.yaml@templates

  - stage:
    displayName: Release
    pool: { vmImage: windows-latest }
    jobs:
      - template: jobs/release/netcore/internal-package.yaml@templates