name: $(Year:yy)$(DayOfYear).$(rev:r)
trigger:
  branches:
    include: [master]
  paths:
    include:
      - 'Analyzers/Audacia.CodeAnalysis.Analyzers/*'
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-latest }

stages:
- stage: Build
  displayName: Build
  jobs:
    - template: pipelines/build/nuget-package.job.yaml@templates
      parameters:
        projects: 'Analyzers/Audacia.CodeAnalysis.Analyzers/src/Audacia.CodeAnalysis.Analyzers/Audacia.CodeAnalysis.Analyzers.csproj'
        tests: 'Analyzers/Audacia.CodeAnalysis.Analyzers/tests/Audacia.CodeAnalysis.Analyzers.Test/Audacia.CodeAnalysis.Analyzers.Test.csproj'

- stage: Release
  displayName: Release
  jobs: [ { template: pipelines/release/internal-nuget-package.job.yaml@templates } ]
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))