name: $(Year:yy)$(DayOfYear).$(rev:r)
trigger:
  branches:
    include: [master]
  paths:
    include:
      - 'Analyzers/Audacia.CodeAnalysis.Analyzers/*'
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-latest }

stages:
- stage: Build
  displayName: Build
  jobs: [ { template: pipelines/build/nuget-package.job.yaml@templates } ]

- stage: Release
  displayName: Release
  jobs: [ { template: pipelines/release/internal-nuget-package.job.yaml@templates } ]