name: $(Year:yy)$(DayOfYear).$(rev:r)
trigger:
  branches:
    include: [master]
  paths:
    include:
      - 'dotnet-roslyn/config/*'
pr: { branches: { include: [master] } }
schedules: [ { cron: "0 0 * * *", displayName: Nightly Build, branches: { include: [ master ] } } ]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-latest }

stages:
- stage: Build
  displayName: Build
  jobs:
    - template: pipelines/build/nuget-package.job.yaml@templates
      parameters:
        projects: 'dotnet-roslyn/config/**/*.csproj'
        tests: 'dotnet-roslyn/config/**/*Tests.csproj'

- stage: Release
  displayName: Release
  jobs:
    - template: pipelines/release/internal-nuget-package.job.yaml@templates
      parameters:
        environment: NuGet Internal (Gated)
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
